"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isOKPO = exports.isOKATO = exports.isOGRNIP = exports.isOGRN = exports.isKPP = exports.isINNLegalEntity = exports.isINNIndividual = exports.isINN = exports.isGS1 = exports.isGLN = exports.isBIK = exports.isPaymentAccount = exports.isCorrespondentAccount = void 0;
var bank_account_1 = require("./bank-account");
Object.defineProperty(exports, "isCorrespondentAccount", { enumerable: true, get: function () { return bank_account_1.isCorrespondentAccount; } });
Object.defineProperty(exports, "isPaymentAccount", { enumerable: true, get: function () { return bank_account_1.isPaymentAccount; } });
Object.defineProperty(exports, "isBIK", { enumerable: true, get: function () { return bank_account_1.isBIK; } });
var gs1_1 = require("./gs1");
Object.defineProperty(exports, "isGLN", { enumerable: true, get: function () { return gs1_1.isGLN; } });
Object.defineProperty(exports, "isGS1", { enumerable: true, get: function () { return gs1_1.isGS1; } });
var inn_1 = require("./inn");
Object.defineProperty(exports, "isINN", { enumerable: true, get: function () { return inn_1.isINN; } });
var individual_1 = require("./inn/individual");
Object.defineProperty(exports, "isINNIndividual", { enumerable: true, get: function () { return individual_1.isINNIndividual; } });
var entity_1 = require("./inn/entity");
Object.defineProperty(exports, "isINNLegalEntity", { enumerable: true, get: function () { return entity_1.isINNLegalEntity; } });
var kpp_1 = require("./kpp");
Object.defineProperty(exports, "isKPP", { enumerable: true, get: function () { return kpp_1.isKPP; } });
var ogrn_1 = require("./ogrn");
Object.defineProperty(exports, "isOGRN", { enumerable: true, get: function () { return ogrn_1.isOGRN; } });
var ogrnip_1 = require("./ogrnip");
Object.defineProperty(exports, "isOGRNIP", { enumerable: true, get: function () { return ogrnip_1.isOGRNIP; } });
var okato_1 = require("./okato");
Object.defineProperty(exports, "isOKATO", { enumerable: true, get: function () { return okato_1.isOKATO; } });
var okpo_1 = require("./okpo");
Object.defineProperty(exports, "isOKPO", { enumerable: true, get: function () { return okpo_1.isOKPO; } });
