"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.matchFilial = exports.isPaymentAccount = exports.isCorrespondentAccount = exports.isBIK = void 0;
var bik_1 = require("./bik");
Object.defineProperty(exports, "isBIK", { enumerable: true, get: function () { return bik_1.isBIK; } });
var correspondentAccount_1 = require("./correspondentAccount");
Object.defineProperty(exports, "isCorrespondentAccount", { enumerable: true, get: function () { return correspondentAccount_1.isCorrespondentAccount; } });
Object.defineProperty(exports, "matchFilial", { enumerable: true, get: function () { return correspondentAccount_1.matchFilial; } });
var paymentAccount_1 = require("./paymentAccount");
Object.defineProperty(exports, "isPaymentAccount", { enumerable: true, get: function () { return paymentAccount_1.isPaymentAccount; } });
